language: cpp

notifications:
  email: false

addons:
  homebrew:
    packages:
      - sdl2
      - giflib
      - jpeg-turbo
      - libpng
      - libtiff
      - webp
    update: true
  apt:
    packages:
      - libsdl2-dev
      - libgif-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libwebp-dev
    update: true

jobs:
  include:
    - os: windows
      name: "Windows Server"
      env:
        - PATH="/c/SAIL/bin:$PATH"
      cache:
        directories:
          - extra/B
    - os: linux
      dist: focal
      name: "Ubuntu 20.04 Focal"
    - os: osx
      osx_image: xcode12.5
      name: "macOS 11.3"
      env:
        - CMAKE_PREFIX_PATH="/usr/local/opt/jpeg-turbo:$CMAKE_PREFIX_PATH"

before_script:
- |-
  case "$TRAVIS_OS_NAME" in
    windows)
      # Build non-existing extra libs
      if [ -d extra/B/bin ]; then
        extra_bin_time=$(stat -c %Y extra/B/bin)
        build_script_time=$(git log --pretty=format:%cd -n 1 --date=unix --date-order -- extra/build)

        if [ $build_script_time -gt $extra_bin_time ]; then
          extra/build
        fi
      else
        extra/build
      fi
    ;;
  esac

script:
- |-
  case "$TRAVIS_OS_NAME" in
    windows)
      mkdir build
      cd build

      cmake -A x64 -DCMAKE_INSTALL_PREFIX="C:\SAIL" -DSAIL_DEV=ON ..
      cmake --build . --config Release --target install

      cd tests
      ctest --verbose -C Release
    ;;
    osx | linux)
      mkdir build
      cd build

      cmake -DCMAKE_BUILD_TYPE=Release -DSAIL_DEV=ON ..
      cmake --build .
      sudo make install

      cd tests
      ctest --verbose
    ;;
  esac
