language: cpp

notifications:
  email: false

addons:
  homebrew:
    packages:
      - sdl2
      - giflib
      - jpeg-turbo
      - libpng
      - libtiff
    update: true
  apt:
    packages:
      - libsdl2-dev
      - libgif-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
    update: true

jobs:
  include:
    - os: windows
      name: "Windows Server"
      env:
        - PATH="/c/SAIL/bin:$PATH"
    - os: linux
      dist: bionic
      name: "Ubuntu 18.04 Bionic"
    - os: linux
      dist: focal
      name: "Ubuntu 20.04 Focal"
    - os: osx
      osx_image:
        - xcode11.3
      name: "macOS 10.14"
      env:
        - CMAKE_PREFIX_PATH="/usr/local/opt/jpeg-turbo:$CMAKE_PREFIX_PATH"
    - os: osx
      osx_image:
        - xcode12.2
      name: "macOS 10.15"
      env:
        - CMAKE_PREFIX_PATH="/usr/local/opt/jpeg-turbo:$CMAKE_PREFIX_PATH"

before_script:
- |-
  case "$TRAVIS_OS_NAME" in
    windows)
      cd extra
      ./build
      cd -
    ;;
  esac

script:
- |-
  case "$TRAVIS_OS_NAME" in
    windows)
      mkdir build
      cd build

      cmake -A x64 -DCMAKE_INSTALL_PREFIX="C:\SAIL" -DSAIL_DEV=ON ..
      cmake --build . --config Release --target install

      cd tests
      ctest --verbose -C Release
    ;;
    osx | linux)
      mkdir build
      cd build

      cmake -DCMAKE_BUILD_TYPE=Release -DSAIL_DEV=ON ..
      cmake --build . --target install

      cd tests
      ctest --verbose
    ;;
  esac
